### ISSUE TITLE
OpenseesSP seems not supporting Initial Stress Material!

### ISSUE THREAD

**Issue by rsamtaslimi** [OpenSees/OpenSees#900]
Dear All,

I have a large model of a suspension bridge, which works fine when I run it on my computer using the regular Opensees. But when I tried the OpenSees SP on the Design-safe online tool, I got the following error. It is not clear to me what is the source of it, but since it is about the uniaxial material and truss elements, I guess it should be related to the Initial Stress Material that I am using to prestress the cables. Does anyone know how to fix it or what is this error exactly?

FEM_ObjectBrokerAllClasses::getNewUniaxialMaterial -  - no UniaxialMaterial type exists for class tag 53
WARNING Truss::recvSelf() - 90102000failed to get a blank Material of type: 53

@mhscott

**Comment by mhscott** [comment]
Thanks for letting me know. ElasticBilin wasn't in the switch statement for getNewUniaxialMaterial. It should work now. https://github.com/OpenSees/OpenSees/pull/901

**Comment by rsamtaslimi** [comment]
Thank you for your prompt response. I just checked it again, but unfortunately, I still get the same error when I run my model on the design-safe. I tried both OpenSeesSP (Stampede2) V3.2 & V3.3. Here is the error that I got:


DomainPartitioner::partition() - Start
DomainPartitioner::partition - Succesfull partition. Now redistributing data accordingly.
  * Identifying components to transfer.
     + Elements.
     + Nodes.
     + Boundary Nodes.
     + MP constraints.
     + MP constraints (2nd pass).
  * Sending nodes.
  * Sending elements.
FEM_ObjectBrokerAllClasses::getNewUniaxialMaterial -  - no UniaxialMaterial type exists for class tag 53
WARNING Truss::recvSelf() - 90102005FEM_ObjectBrokerAllClasses::getNewUniaxialMaterial -  - no UniaxialMaterial type exists for class tag 53failed to get a blank Material of type: 53
FEM_ObjectBrokerAllClasses::getNewUniaxialMaterial -  - no UniaxialMaterial type exists for class tag FEM_ObjectBrokerAllClasses::getNewUniaxialMaterial -  - no UniaxialMaterial type exists for class tag 53FEM_ObjectBrokerAllClasses::getNewUniaxialMaterial -  - no UniaxialMaterial type exists for class tag 53
WARNING Truss::recvSelf() - 90102017FEM_ObjectBrokerAllClasses::getNewUniaxialMaterial -  - no UniaxialMaterial type exists for class tag 53
WARNING Truss::recvSelf() - 90102023FEM_ObjectBrokerAllClasses::getNewUniaxialMaterial -  - no UniaxialMaterial type exists for class tag 53
WARNING Truss::recvSelf() - 90102010failed to get a blank Material of type: 53
53
WARNING Truss::recvSelf() - 90102033failed to get a blank Material of type: 53

WARNING Truss::recvSelf() - 90102028failed to get a blank Material of type: 53
failed to get a blank Material of type: 53
failed to get a blank Material of type: 53

InitStressMaterial::recvSelf() - failed to create Material with classTag 88
WARNING Truss::recvSelf() - 90101000 failed to receive its Material

**Comment by zhuminjie** [comment]
Did you recompile it?

**Comment by rsamtaslimi** [comment]
No, I did not. I am only using the Design-safe online tool to run my model. As far as I know, I do not have access to their database to recompile or change anything.

**Comment by zhuminjie** [comment]
Yeah, then someone should update it. Otherwise, it won't magically update itself.

**Comment by rsamtaslimi** [comment]
That's true. I am not sure who is responsible for doing this. Do you know who I should contact to recompile the OpenSeesSP over the Design-safe after this last change done by Dr. Scott?

**Comment by mhscott** [comment]
Create a ticket at DesignSafe. This repo is not affiliated with DesignSafe or NHERI.

**Comment by rsamtaslimi** [comment]
Thanks for your help. I will. 
But just to make sure, if I download the OpenSeesSP source code from GitHub and compile it on my computer, I should not expect to see that error, as you just fixed it, right?

**Comment by mhscott** [comment]
In theory, yes.

**Comment by rsamtaslimi** [comment]
Wonderful. Thanks for your support. I'll keep you posted.
